/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 15/10/2020, 14:57:56
 */

/**
 *
 * @author Carlos
 */
import javax.swing.*;
import utilitarios.data;
import cadastros.cad_cidades;
public class TelaPrincipal extends javax.swing.JFrame {

    data mostra_data;
    String seta_look = "javax.swing.plaf.metal.MetalLookAndFeel";
    
    /** Creates new form TelaPrincipal */
  
    public TelaPrincipal() {
        initComponents();
        mostra_data = new data();
        mostra_data.le_data();
        Label_data.setText("Data  " +mostra_data.dia_semana+", "+mostra_data.dia + " " + (mostra_data.mes ) + 
                            " " + mostra_data.ano );
        
        timer1.start();
        lookandfeel();
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        bt_clientes = new javax.swing.JButton();
        Logo_empresa = new javax.swing.JLabel();
        bt_cidades = new javax.swing.JButton();
        bt_bairros = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        v_nome_sistema = new javax.swing.JLabel();
        Label_data = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastros = new javax.swing.JMenu();
        menuitem_clientes = new javax.swing.JMenuItem();
        menuitem_cargo = new javax.swing.JMenuItem();
        menuitem_funcionarios = new javax.swing.JMenuItem();
        menuitem_cidades = new javax.swing.JMenuItem();
        menuitem_cidade = new javax.swing.JMenuItem();
        menuitem_bairro = new javax.swing.JMenuItem();
        menuitem_fornecedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_estoque = new javax.swing.JMenu();
        menuitem_implantacao = new javax.swing.JMenuItem();
        menuitem_entrada = new javax.swing.JRadioButtonMenuItem();
        menuitem_saida = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_sair = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        Menu_Relatorios = new javax.swing.JMenu();
        Menu_Utilitarios = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Menu_item_look_metal = new javax.swing.JMenuItem();
        Menu_item_menu_look_liquid = new javax.swing.JMenuItem();
        Menu_item_look_windows = new javax.swing.JMenuItem();
        Menu_item_look_motif = new javax.swing.JMenuItem();
        Menu_Sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Estoque Neri");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        bt_clientes.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\dinheiro2.gif")); // NOI18N
        bt_clientes.setText("Clientes");

        Logo_empresa.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\logo_kyra.gif")); // NOI18N

        bt_cidades.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\old_87.gif")); // NOI18N
        bt_cidades.setText("Cidades");
        bt_cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cidadesActionPerformed(evt);
            }
        });

        bt_bairros.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\descendente.gif")); // NOI18N
        bt_bairros.setText("Bairros");
        bt_bairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bairrosActionPerformed(evt);
            }
        });

        bt_sair.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\sair.gif")); // NOI18N
        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bt_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cidades)
                .addGap(18, 18, 18)
                .addComponent(bt_bairros)
                .addGap(18, 18, 18)
                .addComponent(bt_sair)
                .addGap(123, 123, 123)
                .addComponent(Logo_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_empresa)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_clientes)
                        .addComponent(bt_cidades)
                        .addComponent(bt_bairros)
                        .addComponent(bt_sair)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        v_nome_sistema.setText("Sistema de Estoque Neri");

        Label_data.setText("Data:");

        label_hora.setText("Hora");

        menucadastros.setMnemonic('C');
        menucadastros.setText("Cadastros");
        menucadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucadastrosMouseClicked(evt);
            }
        });

        menuitem_clientes.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\dinheiro2.gif")); // NOI18N
        menuitem_clientes.setMnemonic('C');
        menuitem_clientes.setText("Clientes");
        menucadastros.add(menuitem_clientes);

        menuitem_cargo.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\ferramenta.gif")); // NOI18N
        menuitem_cargo.setMnemonic('a');
        menuitem_cargo.setText("Cargo");
        menucadastros.add(menuitem_cargo);

        menuitem_funcionarios.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\constru.gif")); // NOI18N
        menuitem_funcionarios.setMnemonic('F');
        menuitem_funcionarios.setText("Funcionários");
        menucadastros.add(menuitem_funcionarios);

        menuitem_cidades.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\27.gif")); // NOI18N
        menuitem_cidades.setMnemonic('i');
        menuitem_cidades.setText("Cidades");
        menucadastros.add(menuitem_cidades);

        menuitem_cidade.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\28.gif")); // NOI18N
        menuitem_cidade.setMnemonic('d');
        menuitem_cidade.setText("Cidade");
        menucadastros.add(menuitem_cidade);

        menuitem_bairro.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\30.gif")); // NOI18N
        menuitem_bairro.setMnemonic('B');
        menuitem_bairro.setText("Bairro");
        menucadastros.add(menuitem_bairro);

        menuitem_fornecedores.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\100.gif")); // NOI18N
        menuitem_fornecedores.setMnemonic('o');
        menuitem_fornecedores.setText("Fornecedores");
        menucadastros.add(menuitem_fornecedores);
        menucadastros.add(jSeparator1);

        menu_estoque.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\medidores.gif")); // NOI18N
        menu_estoque.setMnemonic('E');
        menu_estoque.setText("Estoque");

        menuitem_implantacao.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\fichario.gif")); // NOI18N
        menuitem_implantacao.setMnemonic('I');
        menuitem_implantacao.setText("Implantação");
        menu_estoque.add(menuitem_implantacao);

        menuitem_entrada.setMnemonic('E');
        menuitem_entrada.setSelected(true);
        menuitem_entrada.setText("Entrada");
        menuitem_entrada.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\direita.gif")); // NOI18N
        menu_estoque.add(menuitem_entrada);

        menuitem_saida.setMnemonic('S');
        menuitem_saida.setText("Saídas");
        menuitem_saida.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\direita_vermelha.gif")); // NOI18N
        menu_estoque.add(menuitem_saida);

        menucadastros.add(menu_estoque);
        menucadastros.add(jSeparator2);

        menuitem_sair.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\k_exit.gif")); // NOI18N
        menuitem_sair.setMnemonic('S');
        menuitem_sair.setText("Sair");
        menucadastros.add(menuitem_sair);

        jMenuBar1.add(menucadastros);

        menu_consultas.setMnemonic('n');
        menu_consultas.setText("Consultas");
        jMenuBar1.add(menu_consultas);

        Menu_Relatorios.setMnemonic('R');
        Menu_Relatorios.setText("Relatórios");
        jMenuBar1.add(Menu_Relatorios);

        Menu_Utilitarios.setMnemonic('U');
        Menu_Utilitarios.setText("Utilitários");
        Menu_Utilitarios.add(jSeparator3);

        Menu_item_look_metal.setText("Look Metal");
        Menu_item_look_metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_item_look_metalActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(Menu_item_look_metal);

        Menu_item_menu_look_liquid.setText("Look Liquid");
        Menu_item_menu_look_liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_item_menu_look_liquidActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(Menu_item_menu_look_liquid);

        Menu_item_look_windows.setText("Look Windows");
        Menu_item_look_windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_item_look_windowsActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(Menu_item_look_windows);

        Menu_item_look_motif.setText("Look Motif");
        Menu_item_look_motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_item_look_motifActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(Menu_item_look_motif);

        jMenuBar1.add(Menu_Utilitarios);

        Menu_Sair.setMnemonic('S');
        Menu_Sair.setText("Sair");
        Menu_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(v_nome_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(Label_data)
                .addGap(18, 18, 18)
                .addComponent(label_hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(v_nome_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-450)/2, 800, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        
        mostra_data.le_hora();
        label_hora.setText("Hora Local:  "+ mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void bt_bairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bairrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bairrosActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_sairActionPerformed

    private void Menu_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Menu_SairMouseClicked

    private void Menu_item_look_metalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_item_look_metalActionPerformed
        // TODO add your handling code here:
        seta_look="javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_Menu_item_look_metalActionPerformed

    private void Menu_item_menu_look_liquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_item_menu_look_liquidActionPerformed
        // TODO add your handling code here:
        seta_look="com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_Menu_item_menu_look_liquidActionPerformed

    private void Menu_item_look_windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_item_look_windowsActionPerformed
        // TODO add your handling code here:
        seta_look="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_Menu_item_look_windowsActionPerformed

    private void Menu_item_look_motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_item_look_motifActionPerformed
        // TODO add your handling code here:
        seta_look="com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_Menu_item_look_motifActionPerformed

    private void bt_cidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cidadesActionPerformed
        // TODO add your handling code here:
        new cad_cidades().show();
    }//GEN-LAST:event_bt_cidadesActionPerformed

    private void menucadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucadastrosMouseClicked
        // TODO add your handling code here:
        new cadastros.cad_cidades().show();
    }//GEN-LAST:event_menucadastrosMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_data;
    private javax.swing.JLabel Logo_empresa;
    private javax.swing.JMenu Menu_Relatorios;
    private javax.swing.JMenu Menu_Sair;
    private javax.swing.JMenu Menu_Utilitarios;
    private javax.swing.JMenuItem Menu_item_look_metal;
    private javax.swing.JMenuItem Menu_item_look_motif;
    private javax.swing.JMenuItem Menu_item_look_windows;
    private javax.swing.JMenuItem Menu_item_menu_look_liquid;
    private javax.swing.JButton bt_bairros;
    private javax.swing.JButton bt_cidades;
    private javax.swing.JButton bt_clientes;
    private javax.swing.JButton bt_sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel label_hora;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_estoque;
    private javax.swing.JMenu menucadastros;
    private javax.swing.JMenuItem menuitem_bairro;
    private javax.swing.JMenuItem menuitem_cargo;
    private javax.swing.JMenuItem menuitem_cidade;
    private javax.swing.JMenuItem menuitem_cidades;
    private javax.swing.JMenuItem menuitem_clientes;
    private javax.swing.JRadioButtonMenuItem menuitem_entrada;
    private javax.swing.JMenuItem menuitem_fornecedores;
    private javax.swing.JMenuItem menuitem_funcionarios;
    private javax.swing.JMenuItem menuitem_implantacao;
    private javax.swing.JRadioButtonMenuItem menuitem_saida;
    private javax.swing.JMenuItem menuitem_sair;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private javax.swing.JLabel v_nome_sistema;
    // End of variables declaration//GEN-END:variables

    public void lookandfeel()
    {
         try
        {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception erro) 
        {
           JOptionPane.showMessageDialog(null,erro);
        }
    }
}
