
import cadastros.cad_cidades;
import javax.swing.*;
import utilitarios.data;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos
 */
public class TelaPrincipal extends javax.swing.JFrame {
      data mostra_data;

      String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
      
      /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        mostra_data = new data();
        mostra_data.le_data();
        Label_data.setText("Data "+mostra_data.dia_semana+", "+mostra_data.dia+" de "+
           mostra_data.mes+" de "+mostra_data.ano);
        
        timer1.start();
        lookandfell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        Button_clientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_cidades = new javax.swing.JButton();
        Button_bairros = new javax.swing.JButton();
        Button_sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Label_data = new javax.swing.JLabel();
        Label_hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_cadastros = new javax.swing.JMenu();
        Menuitem_clientes = new javax.swing.JMenuItem();
        Menuitem_funcionarios = new javax.swing.JMenuItem();
        Menuitem_cargo = new javax.swing.JMenuItem();
        Menuitem_cidades = new javax.swing.JMenuItem();
        Menuitem_Cidade = new javax.swing.JMenuItem();
        Menuitem_bairro = new javax.swing.JMenuItem();
        Menuitem_fornecedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Menu_estoque = new javax.swing.JMenu();
        Menuitem_implantacao = new javax.swing.JMenuItem();
        Menuitem_entradas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Menuitem_sair = new javax.swing.JMenuItem();
        Menu_Consultas = new javax.swing.JMenu();
        Menu_relatorios = new javax.swing.JMenu();
        Menu_utilitarios = new javax.swing.JMenu();
        look_and_fell_padaro = new javax.swing.JMenuItem();
        look_and_fell_motif = new javax.swing.JMenuItem();
        look_and_fell_Liquid = new javax.swing.JMenuItem();
        Menu_sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Curso de JAVA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        Button_clientes.setBackground(new java.awt.Color(0, 204, 204));
        Button_clientes.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\jinit.gif")); // NOI18N
        Button_clientes.setText("Clientes");

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));

        Button_cidades.setBackground(new java.awt.Color(0, 204, 204));
        Button_cidades.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\insrec.gif")); // NOI18N
        Button_cidades.setText("Cidades");
        Button_cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cidadesActionPerformed(evt);
            }
        });

        Button_bairros.setBackground(new java.awt.Color(0, 204, 204));
        Button_bairros.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\navgn.gif")); // NOI18N
        Button_bairros.setText("Bairros");

        Button_sair.setBackground(new java.awt.Color(0, 204, 204));
        Button_sair.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\k_exit.gif")); // NOI18N
        Button_sair.setText("Sair");
        Button_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_clientes)
                        .addGap(36, 36, 36)
                        .addComponent(Button_cidades, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Button_bairros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Button_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_clientes)
                    .addComponent(Button_cidades, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_bairros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\38.gif")); // NOI18N
        jLabel2.setText("Responsaveis Carlos e Denise");

        Label_data.setText("Data: ");

        Label_hora.setText("Hora: ");

        Menu_cadastros.setMnemonic('C');
        Menu_cadastros.setText("Cadastros");

        Menuitem_clientes.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\jinit.gif")); // NOI18N
        Menuitem_clientes.setMnemonic('C');
        Menuitem_clientes.setText("Clientes");
        Menu_cadastros.add(Menuitem_clientes);

        Menuitem_funcionarios.setMnemonic('F');
        Menuitem_funcionarios.setText("Funcionários");
        Menu_cadastros.add(Menuitem_funcionarios);

        Menuitem_cargo.setMnemonic('G');
        Menuitem_cargo.setText("Cargo");
        Menu_cadastros.add(Menuitem_cargo);

        Menuitem_cidades.setMnemonic('I');
        Menuitem_cidades.setText("Cidades");
        Menuitem_cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuitem_cidadesActionPerformed(evt);
            }
        });
        Menu_cadastros.add(Menuitem_cidades);

        Menuitem_Cidade.setMnemonic('D');
        Menuitem_Cidade.setText("cidade");
        Menuitem_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuitem_CidadeActionPerformed(evt);
            }
        });
        Menu_cadastros.add(Menuitem_Cidade);

        Menuitem_bairro.setMnemonic('B');
        Menuitem_bairro.setText("Bairro");
        Menu_cadastros.add(Menuitem_bairro);

        Menuitem_fornecedores.setMnemonic('O');
        Menuitem_fornecedores.setText("Fornecedores");
        Menu_cadastros.add(Menuitem_fornecedores);
        Menu_cadastros.add(jSeparator1);

        Menu_estoque.setMnemonic('E');
        Menu_estoque.setText("Estoque");

        Menuitem_implantacao.setText("Implantação");
        Menu_estoque.add(Menuitem_implantacao);

        Menuitem_entradas.setText("Entradas");
        Menu_estoque.add(Menuitem_entradas);

        jMenuItem3.setText("Saidas");
        Menu_estoque.add(jMenuItem3);

        Menu_cadastros.add(Menu_estoque);
        Menu_cadastros.add(jSeparator2);

        Menuitem_sair.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\Imagens\\k_exit.gif")); // NOI18N
        Menuitem_sair.setMnemonic('S');
        Menuitem_sair.setText("Sair");
        Menu_cadastros.add(Menuitem_sair);

        jMenuBar1.add(Menu_cadastros);

        Menu_Consultas.setMnemonic('N');
        Menu_Consultas.setText("Consultas");
        jMenuBar1.add(Menu_Consultas);

        Menu_relatorios.setMnemonic('R');
        Menu_relatorios.setText("Relatórios");
        jMenuBar1.add(Menu_relatorios);

        Menu_utilitarios.setMnemonic('U');
        Menu_utilitarios.setText("Utilitários");
        Menu_utilitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_utilitariosActionPerformed(evt);
            }
        });

        look_and_fell_padaro.setText("Look And Fell Padaro");
        look_and_fell_padaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                look_and_fell_padaroActionPerformed(evt);
            }
        });
        Menu_utilitarios.add(look_and_fell_padaro);

        look_and_fell_motif.setText("Look And Fell Motif");
        look_and_fell_motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                look_and_fell_motifActionPerformed(evt);
            }
        });
        Menu_utilitarios.add(look_and_fell_motif);

        look_and_fell_Liquid.setText("Look And Fell  Liquid");
        look_and_fell_Liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                look_and_fell_LiquidActionPerformed(evt);
            }
        });
        Menu_utilitarios.add(look_and_fell_Liquid);

        jMenuBar1.add(Menu_utilitarios);

        Menu_sair.setMnemonic('S');
        Menu_sair.setText("Sair");
        Menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_hora)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_data)
                    .addComponent(Label_hora))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        setBounds(0, 0, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void Menuitem_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuitem_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuitem_CidadeActionPerformed

    private void Button_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Button_sairActionPerformed

    private void Menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_sairMouseClicked
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_Menu_sairMouseClicked

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
                mostra_data.le_hora();
                Label_hora.setText("Hora Atual: "+mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void look_and_fell_padaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_look_and_fell_padaroActionPerformed
            seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
            lookandfell();
    }//GEN-LAST:event_look_and_fell_padaroActionPerformed

    private void Menu_utilitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_utilitariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_utilitariosActionPerformed

    private void look_and_fell_motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_look_and_fell_motifActionPerformed
            seta_look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            lookandfell();

    }//GEN-LAST:event_look_and_fell_motifActionPerformed

    private void look_and_fell_LiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_look_and_fell_LiquidActionPerformed
            seta_look = "com.cursos.liquid.liquidLookAndFeel";
            lookandfell();
    }//GEN-LAST:event_look_and_fell_LiquidActionPerformed

    private void Button_cidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cidadesActionPerformed
        // TODO add your handling code here:
        new cad_cidades().show();
    }//GEN-LAST:event_Button_cidadesActionPerformed

    private void Menuitem_cidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuitem_cidadesActionPerformed
            new cad_cidades().show();
    }//GEN-LAST:event_Menuitem_cidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_bairros;
    private javax.swing.JButton Button_cidades;
    private javax.swing.JButton Button_clientes;
    private javax.swing.JButton Button_sair;
    private javax.swing.JLabel Label_data;
    private javax.swing.JLabel Label_hora;
    private javax.swing.JMenu Menu_Consultas;
    private javax.swing.JMenu Menu_cadastros;
    private javax.swing.JMenu Menu_estoque;
    private javax.swing.JMenu Menu_relatorios;
    private javax.swing.JMenu Menu_sair;
    private javax.swing.JMenu Menu_utilitarios;
    private javax.swing.JMenuItem Menuitem_Cidade;
    private javax.swing.JMenuItem Menuitem_bairro;
    private javax.swing.JMenuItem Menuitem_cargo;
    private javax.swing.JMenuItem Menuitem_cidades;
    private javax.swing.JMenuItem Menuitem_clientes;
    private javax.swing.JMenuItem Menuitem_entradas;
    private javax.swing.JMenuItem Menuitem_fornecedores;
    private javax.swing.JMenuItem Menuitem_funcionarios;
    private javax.swing.JMenuItem Menuitem_implantacao;
    private javax.swing.JMenuItem Menuitem_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem look_and_fell_Liquid;
    private javax.swing.JMenuItem look_and_fell_motif;
    private javax.swing.JMenuItem look_and_fell_padaro;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

    
        // Criar um Método
        public void lookandfell()
        {
         try                 
            {
                UIManager.setLookAndFeel(seta_look);
                SwingUtilities.updateComponentTreeUI(this);
            }
            catch(Exception erro)
            {
                JOptionPane.showMessageDialog(null, erro);
            }
        }


        /*//UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.metal.MetalLookAndFeel");
        */        

}
