/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 15/10/2020, 14:57:56
 */

/**
 *
 * @author Carlos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        data mostra_data = new data();
        mostra_data.le_data();
        Label_data.setText("Data  " +mostra_data.dia_semana+", "+mostra_data.dia + " " + (mostra_data.mes ) + 
                            " " + mostra_data.ano );
        
        mostra_data.le_hora();
        label_hora.setText("Horário: " + mostra_data.hora);
        
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        bt_clientes = new javax.swing.JButton();
        Logo_empresa = new javax.swing.JLabel();
        v_nome_sistema = new javax.swing.JLabel();
        Label_data = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastros = new javax.swing.JMenu();
        menuitem_clientes = new javax.swing.JMenuItem();
        menuitem_cargo = new javax.swing.JMenuItem();
        menuitem_funcionarios = new javax.swing.JMenuItem();
        menuitem_cidades = new javax.swing.JMenuItem();
        menuitem_cidade = new javax.swing.JMenuItem();
        menuitem_bairro = new javax.swing.JMenuItem();
        menuitem_fornecedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_estoque = new javax.swing.JMenu();
        menuitem_implantacao = new javax.swing.JMenuItem();
        menuitem_entrada = new javax.swing.JRadioButtonMenuItem();
        menuitem_saida = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_sair = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        Menu_Relatorios = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Estoque Neri");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        bt_clientes.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\dinheiro2.gif")); // NOI18N
        bt_clientes.setText("Clientes");

        Logo_empresa.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Imagens\\logo_kyra.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bt_clientes)
                .addGap(430, 430, 430)
                .addComponent(Logo_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_empresa)
                    .addComponent(bt_clientes))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        v_nome_sistema.setText("Sistema de Estoque Neri");

        Label_data.setText("Data:");

        label_hora.setText("Hora");

        menucadastros.setMnemonic('C');
        menucadastros.setText("Cadastros");

        menuitem_clientes.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\dinheiro2.gif")); // NOI18N
        menuitem_clientes.setMnemonic('C');
        menuitem_clientes.setText("Clientes");
        menucadastros.add(menuitem_clientes);

        menuitem_cargo.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\ferramenta.gif")); // NOI18N
        menuitem_cargo.setMnemonic('a');
        menuitem_cargo.setText("Cargo");
        menucadastros.add(menuitem_cargo);

        menuitem_funcionarios.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\constru.gif")); // NOI18N
        menuitem_funcionarios.setMnemonic('F');
        menuitem_funcionarios.setText("Funcionários");
        menucadastros.add(menuitem_funcionarios);

        menuitem_cidades.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\27.gif")); // NOI18N
        menuitem_cidades.setMnemonic('i');
        menuitem_cidades.setText("Cidades");
        menucadastros.add(menuitem_cidades);

        menuitem_cidade.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\28.gif")); // NOI18N
        menuitem_cidade.setMnemonic('d');
        menuitem_cidade.setText("Cidade");
        menucadastros.add(menuitem_cidade);

        menuitem_bairro.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\30.gif")); // NOI18N
        menuitem_bairro.setMnemonic('B');
        menuitem_bairro.setText("Bairro");
        menucadastros.add(menuitem_bairro);

        menuitem_fornecedores.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\100.gif")); // NOI18N
        menuitem_fornecedores.setMnemonic('o');
        menuitem_fornecedores.setText("Fornecedores");
        menucadastros.add(menuitem_fornecedores);
        menucadastros.add(jSeparator1);

        menu_estoque.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\medidores.gif")); // NOI18N
        menu_estoque.setMnemonic('E');
        menu_estoque.setText("Estoque");

        menuitem_implantacao.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\fichario.gif")); // NOI18N
        menuitem_implantacao.setMnemonic('I');
        menuitem_implantacao.setText("Implantação");
        menu_estoque.add(menuitem_implantacao);

        menuitem_entrada.setMnemonic('E');
        menuitem_entrada.setSelected(true);
        menuitem_entrada.setText("Entrada");
        menuitem_entrada.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\direita.gif")); // NOI18N
        menu_estoque.add(menuitem_entrada);

        menuitem_saida.setMnemonic('S');
        menuitem_saida.setText("Saídas");
        menuitem_saida.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\direita_vermelha.gif")); // NOI18N
        menu_estoque.add(menuitem_saida);

        menucadastros.add(menu_estoque);
        menucadastros.add(jSeparator2);

        menuitem_sair.setIcon(new javax.swing.ImageIcon("C:\\Desenv\\Aulas_Java\\estoque\\Icones\\k_exit.gif")); // NOI18N
        menuitem_sair.setMnemonic('S');
        menuitem_sair.setText("Sair");
        menucadastros.add(menuitem_sair);

        jMenuBar1.add(menucadastros);

        menu_consultas.setMnemonic('n');
        menu_consultas.setText("Consultas");
        jMenuBar1.add(menu_consultas);

        Menu_Relatorios.setMnemonic('R');
        Menu_Relatorios.setText("Relatórios");
        jMenuBar1.add(Menu_Relatorios);

        jMenu4.setMnemonic('U');
        jMenu4.setText("Utilitários");
        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('S');
        jMenu5.setText("Sair");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(v_nome_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(Label_data)
                .addGap(18, 18, 18)
                .addComponent(label_hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(v_nome_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-450)/2, 800, 450);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_data;
    private javax.swing.JLabel Logo_empresa;
    private javax.swing.JMenu Menu_Relatorios;
    private javax.swing.JButton bt_clientes;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel label_hora;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_estoque;
    private javax.swing.JMenu menucadastros;
    private javax.swing.JMenuItem menuitem_bairro;
    private javax.swing.JMenuItem menuitem_cargo;
    private javax.swing.JMenuItem menuitem_cidade;
    private javax.swing.JMenuItem menuitem_cidades;
    private javax.swing.JMenuItem menuitem_clientes;
    private javax.swing.JRadioButtonMenuItem menuitem_entrada;
    private javax.swing.JMenuItem menuitem_fornecedores;
    private javax.swing.JMenuItem menuitem_funcionarios;
    private javax.swing.JMenuItem menuitem_implantacao;
    private javax.swing.JRadioButtonMenuItem menuitem_saida;
    private javax.swing.JMenuItem menuitem_sair;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private javax.swing.JLabel v_nome_sistema;
    // End of variables declaration//GEN-END:variables

}
